from __future__ import annotations

from yonerai_cli.tui.keymap import (
    JAPANESE_SLASH_ALIASES,
    NUMBERED_VALUE_GROUPS,
    SLASH_COMMANDS,
    SLASH_VALUE_GROUPS,
    SlashCommandSpec,
    SlashValueSpec,
    build_prompt_completer as _build_prompt_completer,
    slash_command_meta,
    slash_command_value_group,
    slash_command_words,
    slash_value_meta,
    slash_value_words,
)
from yonerai_cli.tui.palette import format_command_palette, slash_command_summary
from yonerai_cli.tui.renderer import (
    COMMAND_PALETTE_TRIGGER,
    open_choice_dialog,
    open_command_palette,
    prompt_line,
    prompt_toolkit_available,
    prompt_toolkit_console_ready,
    render_panel,
    render_text_block,
    rich_available,
    run_with_status,
    tui_capability_report,
)

__all__ = [
    "JAPANESE_SLASH_ALIASES",
    "NUMBERED_VALUE_GROUPS",
    "SLASH_COMMANDS",
    "SLASH_VALUE_GROUPS",
    "SlashCommandSpec",
    "SlashValueSpec",
    "_build_prompt_completer",
    "COMMAND_PALETTE_TRIGGER",
    "open_choice_dialog",
    "open_command_palette",
    "prompt_line",
    "prompt_toolkit_available",
    "prompt_toolkit_console_ready",
    "render_panel",
    "render_text_block",
    "rich_available",
    "run_with_status",
    "format_command_palette",
    "slash_command_meta",
    "slash_command_summary",
    "slash_command_value_group",
    "slash_command_words",
    "slash_value_meta",
    "slash_value_words",
    "tui_capability_report",
]
