from __future__ import annotations


COMMAND_ALIASES = {
    "/?": "/help",
    "/状態": "/status",
    "/ホーム": "/status",
    "/status": "/status",
    "/home": "/status",
    "/ヘルプ": "/help",
    "/help": "/help",
    "/コマンド": "/palette",
    "/パレット": "/palette",
    "/palette": "/palette",
    "/commands": "/palette",
    "/設定": "/settings",
    "/settings": "/settings",
    "/モデル": "/models",
    "/model": "/models",
    "/models": "/models",
    "/安全": "/safety",
    "/safety": "/safety",
    "/ポリシー": "/policy",
    "/方針": "/policy",
    "/policy": "/policy",
    "/提供元": "/providers",
    "/プロバイダー": "/providers",
    "/providers": "/providers",
    "/履歴": "/runs",
    "/runs": "/runs",
    "/タスク": "/tasks",
    "/tasks": "/tasks",
    "/表示": "/show",
    "/show": "/show",
    "/エージェント": "/agents",
    "/agents": "/agents",
    "/agent": "/agents",
    "/コンテキスト": "/context",
    "/参照": "/context",
    "/context": "/context",
    "/references": "/context",
    "/モード": "/mode",
    "/mode": "/mode",
    "/計画": "/plan",
    "/plan": "/plan",
    "/レビュー": "/review",
    "/review": "/review",
    "/権限": "/permissions",
    "/permissions": "/permissions",
    "/認証": "/auth",
    "/auth": "/auth",
    "/API": "/api",
    "/api": "/api",
    "/公式": "/api",
    "/同期": "/sync",
    "/sync": "/sync",
    "/プライバシー": "/privacy",
    "/privacy": "/privacy",
    "/記憶": "/memory",
    "/メモリ": "/memory",
    "/memory": "/memory",
    "/自己進化": "/evolve",
    "/evolve": "/evolve",
    "/ローカルllm": "/local-llm",
    "/ローカルLLM": "/local-llm",
    "/local-llm": "/local-llm",
    "/llm": "/local-llm",
    "/更新": "/update",
    "/update": "/update",
    "/更新通知": "/update-notice",
    "/update-notice": "/update-notice",
    "/言語": "/language",
    "/language": "/language",
    "/提供元選択": "/provider",
    "/プロバイダー選択": "/provider",
    "/provider": "/provider",
    "/承認": "/approval",
    "/approval": "/approval",
    "/ファイル": "/file-access",
    "/ファイルアクセス": "/file-access",
    "/file-access": "/file-access",
    "/履歴記録": "/ledger",
    "/ledger": "/ledger",
    "/ライブ": "/live-provider",
    "/ライブ接続": "/live-provider",
    "/live": "/live-provider",
    "/live-provider": "/live-provider",
    "/ネットワーク": "/network",
    "/network": "/network",
    "/選択": "/select",
    "/select": "/select",
    "/終了": "/quit",
    "/quit": "/quit",
    "/exit": "/quit",
    "/q": "/quit",
}
VALUE_ALIASES = {
    "日本語": "ja",
    "英語": "en",
    "自動": "auto",
    "モック": "mock",
    "ローカル": "local",
    "OpenAI互換": "openai-compatible",
    "openai互換": "openai-compatible",
    "アンソロピック": "anthropic",
    "ジェミニ": "gemini",
    "確認": "prompt",
    "毎回確認": "prompt",
    "拒否": "deny",
    "計画": "plan_readonly",
    "読み取り": "plan_readonly",
    "読み取り専用": "plan_readonly",
    "plan": "plan_readonly",
    "plan-readonly": "plan_readonly",
    "安全実行": "build_safe",
    "ビルド": "build_safe",
    "構築": "build_safe",
    "build": "build_safe",
    "execute-safe": "build_safe",
    "レビュー": "review",
    "査読": "review",
    "記憶": "memory",
    "メモリ": "memory",
    "read-only": "read_only",
    "readonly": "read_only",
    "読み取りのみ": "read_only",
    "自動安全": "auto_safe",
    "auto-safe": "auto_safe",
    "危険時確認": "ask_before_risky",
    "ask-before-risky": "ask_before_risky",
    "ドライランのみ": "dry_run_only",
    "dry-run-only": "dry_run_only",
    "ワークスペース内のみ": "workspace_only",
    "ワークスペースのみ": "workspace_only",
    "無効": "disabled",
    "オン": "on",
    "有効": "on",
    "履歴オン": "on",
    "オフ": "off",
    "履歴オフ": "off",
}

def canonical_command(value: str) -> str:
    raw = value.strip()
    return COMMAND_ALIASES.get(raw, COMMAND_ALIASES.get(raw.lower(), raw.lower()))


def canonical_value(value: str) -> str:
    raw = value.strip()
    return VALUE_ALIASES.get(raw, VALUE_ALIASES.get(raw.lower(), raw))


def canonical_agent_mode_value(value: str) -> str:
    normalized = canonical_value(value)
    return "plan_readonly" if normalized == "read_only" else normalized
